/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlitsRouteImport } from './routes/slits'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CombinationsRouteImport } from './routes/combinations'
import { Route as CoilsRouteImport } from './routes/coils'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'

const SlitsRoute = SlitsRouteImport.update({
  id: '/slits',
  path: '/slits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinationsRoute = CombinationsRouteImport.update({
  id: '/combinations',
  path: '/combinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CoilsRoute = CoilsRouteImport.update({
  id: '/coils',
  path: '/coils',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/coils': typeof CoilsRoute
  '/combinations': typeof CombinationsRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/slits': typeof SlitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/plans'
    | '/products'
    | '/slits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/plans'
    | '/products'
    | '/slits'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/coils'
    | '/combinations'
    | '/dashboard'
    | '/plans'
    | '/products'
    | '/slits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  CoilsRoute: typeof CoilsRoute
  CombinationsRoute: typeof CombinationsRoute
  DashboardRoute: typeof DashboardRoute
  PlansRoute: typeof PlansRoute
  ProductsRoute: typeof ProductsRoute
  SlitsRoute: typeof SlitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slits': {
      id: '/slits'
      path: '/slits'
      fullPath: '/slits'
      preLoaderRoute: typeof SlitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combinations': {
      id: '/combinations'
      path: '/combinations'
      fullPath: '/combinations'
      preLoaderRoute: typeof CombinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coils': {
      id: '/coils'
      path: '/coils'
      fullPath: '/coils'
      preLoaderRoute: typeof CoilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  CoilsRoute: CoilsRoute,
  CombinationsRoute: CombinationsRoute,
  DashboardRoute: DashboardRoute,
  PlansRoute: PlansRoute,
  ProductsRoute: ProductsRoute,
  SlitsRoute: SlitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
